### ISSUE TITLE
README example code is broken. 

### ISSUE THREAD

**Issue by aomi** [Chris-Bitler/jest-discordjs-mocks#2]
Hello,

I tried using setting up a scenario similar to one found in the README but get the following error.
```
 FAIL  src/__tests__/index.test.ts
  messageRouter
    ✕ works properly (1 ms)

  ● messageRouter › works properly

    TypeError: Cannot read property 'client' of undefined

      20 |     it('works properly', async () => {
      21 |         const message = new MockMessage();
    > 22 |         const channel = new MockTextChannel();
         |                         ^
      23 |
      24 |         message.content = '!ping';
      25 |         message.channel = channel;

      at new GuildChannel (node_modules/discord.js/src/structures/GuildChannel.js:28:17)
      at new TextChannel (node_modules/discord.js/src/structures/TextChannel.js:21:5)
      at src/__tests__/index.test.ts:22:25
      at step (src/__tests__/index.test.ts:33:23)
      at Object.next (src/__tests__/index.test.ts:14:53)
      at src/__tests__/index.test.ts:8:71
      at Object.<anonymous>.__awaiter (src/__tests__/index.test.ts:4:12)
      at Object.<anonymous> (src/__tests__/index.test.ts:20:26)
```
Test case:
```
     const message = new MockMessage();
     const channel = new MockTextChannel();

     message.content = '!ping';
     message.channel = channel;

     const tedis = new Tedis();

     messageRouter(tedis)(message);  
     expect(MockedTedis).toBeCalled();
```

I am wondering if the library is broken or I am doing something wrong. Thanks in advance 🙇

**Comment by codewithtyler** [comment]
I don't think you're doing anything wrong. I ran into this issue as well. I'll post back here if I figure out the issue. I suspect the README documentation is just missing some info.

**Comment by samhwang** [comment]
Hey @PallasMedia have you figured out what the issue was ? I was trying to install this into my project as well and it failed at the same spot. :(

@Chris-Bitler any chance we can have an update on the documentations ?

**Comment by codewithtyler** [comment]
No, I ended up taking a different approach.
